### ISSUE TITLE
addKey.sh: not found

### ISSUE THREAD

**Issue by idl3** [wercker/step-add-ssh-key#19]
This error appeared while running an auto trigger from Pipeline "build" to Pipeline "deploy-staging"

The pipeline error as follows
```sh
source "/pipeline/add-ssh-key-6a3afc43-117d-40f4-be89-f982db71717c/run.sh" < /dev/null
/bin/sh: /pipeline/add-ssh-key-6a3afc43-117d-40f4-be89-f982db71717c/run.sh: line 29: /pipeline/add-ssh-key-6a3afc43-117d-40f4-be89-f982db71717c/addKey.sh: not found
```

wercker.yml file snippet
```yaml
deploy-staging:
  steps:
    - bundle-install

    - add-ssh-key:
        keyname: STAGING_DEPLOY

    - script:
        name: Deploy staging
        code: cap staging deploy
```

This same code was working on our codebase previously.

Any help would be great

**Comment by dldnh** [comment]
which box have you specified in your wercker.yml?

**Comment by idl3** [comment]
Ah, @dldnh I'm using a custom created docker image. `idl3/rails-base-2.4.1`

I suppose this base image will have to install this step into it?
I'm going to close this since it's most likely due to a custom image.

Could you help direct me to the right resource for enabling this step in a custom box?

**Comment by idl3** [comment]
[Update] Managed to fix the deployment by overriding the box used on the deploy step to:
```yaml
deploy-staging:
  box: ruby:2.4.1
  steps:
    - bundle-install

    - add-ssh-key:
        keyname: STAGING_DEPLOY

    - script:
        name: Deploy staging
        code: cap staging deploy
```
